<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26569" started-at="2019-01-15T07:55:28Z" finished-at="2019-01-15T07:55:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26569" started-at="2019-01-15T07:55:28Z" finished-at="2019-01-15T07:55:54Z">
      <class name="RestProject.Test.Executable">
        <test-method status="FAIL" signature="createNewUsers()[pri:1, instance:RestProject.Test.Executable@d44fc21]" name="createNewUsers" duration-ms="24130" started-at="2019-01-15T13:25:28Z" finished-at="2019-01-15T13:25:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[     George is not present     ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:      George is not present     
	at org.testng.Assert.fail(Assert.java:93)
	at RestProject.Test.Executable.createNewUsers(Executable.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUsers -->
        <test-method status="PASS" signature="UpdateNewUsers()[pri:2, instance:RestProject.Test.Executable@d44fc21]" name="UpdateNewUsers" duration-ms="960" started-at="2019-01-15T13:25:52Z" finished-at="2019-01-15T13:25:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateNewUsers -->
        <test-method status="PASS" signature="DeleteNewUsers()[pri:3, instance:RestProject.Test.Executable@d44fc21]" name="DeleteNewUsers" duration-ms="1450" started-at="2019-01-15T13:25:53Z" finished-at="2019-01-15T13:25:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteNewUsers -->
      </class> <!-- RestProject.Test.Executable -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
